#!/bin/bash
#
# Program: qscript_functions
# Author:  Eric Deutsch
#
# Copyright (C) 2009-2022 by Eric Deutsch
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the Apache 2.0 License.
#                                                                           
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# full license for more details.                                  
#                                                                           
# You should have received a copy of the Apache 2.0 License
# along with this library; if not, please see the original source at
# https://github.com/edeutsch/qscripts
# 
# Institute for Systems Biology
# 401 Terry Avenue North
# Seattle WA 98109 USA
# spctools@systemsbiology.org
#
# Common BASH Shell Functions used by the set of "q" scripts used to submit
# jobs to run some of the various TPP programs
#


# Simple "die" and warn functions
function die () {
   echo "$(basename $0): ${1:-"Unknown error"}" 1>&2
   exit 1
}

function warn () {
   echo "$(basename $0): ${1:-"Unknown error"}" 1>&2
}


# Turn a relative to absolute path
# From http://unix.derkeiler.com/Newsgroups/comp.unix.programmer/2005-01/0206.html
function rel2abs() {
  [ "$#" -eq 1 ] || return 1
  ls -Ld -- "$1" > /dev/null || return
  dir=$(dirname -- "$1" && echo .) || return
  dir=$(cd -P -- "${dir%??}" && pwd -P && echo .) || return
  dir=${dir%??}
  file=$(basename -- "$1" && echo .) || return
  file=${file%??}
  case $dir in
    /) printf '%s\n' "/$file";;
    /*) printf '%s\n' "$dir/$file";;
    *) return 1;;
  esac
  return 0
} 


# Function to verify that we're running on an old or new cluster submission host
function assert_old_or_new_cluster_head_node () {
if [ -z "$HOST" ]; then
  die "ERROR: Environment variable HOST is not defined. It should have been set automatically in /proteomics/sw/.bashrc"
fi

if [ "$HOST" != "regis" ] && [ "$HOST" != "regis-dev" ] && [ "$HOST" != "regis-web" ]; then
  die "ERROR: Please execute this from regis (or regis-dev, regis-web for special applications)"
fi
}


# Function to verify that we're running on a new cluster submission host
function assert_new_cluster_head_node () {
if [ -z "$HOST" ]; then
  die "ERROR: Environment variable HOST is not defined. It should have been set automatically in /proteomics/sw/.bashrc"
fi

if [ "$HOST" != "regis" ] && [ "$HOST" != "regis-dev" ] && [ "$HOST" != "regis-web" ]; then
  die "ERROR: Please execute this from a cluster submission host like regis"
fi
}

